// fixture.mjs — write a synthetic photometric capture to disk as a real bundle.
//
//   node relight/tools/fixture.mjs <out-dir> [--grain=0.2] [--sphere] [--drift]
//                                            [--size=340] [--shots=6] [--flat]
//
// Two jobs.
//
// 1. It is the self-test for score-real.mjs. That harness reads files, decodes
//    them, registers, reads a sphere, solves, and scores — a lot of machinery
//    between a photograph and a number, and none of it is exercised by the
//    synthetic bench in validate.mjs, which hands arrays straight to the maths.
//    Here the surface's true normals are known, so the whole chain can be run
//    end to end and the answer checked against truth. It is the same practice as
//    HANDOFF.md §11 (how this is worked), applied to the file plumbing rather than to
// the algorithm.
//
// 2. It shows what a capture bundle looks like before you shoot one. Reading a
//    worked example beats reading a schema, and the two faults that cannot be
//    repaired after the fact — a rank-deficient rig, an undersized sphere — are
//    easier to avoid having seen a good one.
//
// The exposures are written as PNG because the format is lossless and because
// tools/png.js reads it with no dependencies, so the self-test needs no browser.

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { encodePNG } from './png.js';

globalThis.ImageData = class {
  constructor(w, h) { this.width = w; this.height = h; this.data = new Uint8ClampedArray(w * h * 4); }
};

const { synthesizeCaptureSet } = await import(new URL('../src/synth.js', import.meta.url));
const { resample } = await import(new URL('../src/register.js', import.meta.url));

const argv = process.argv.slice(2);
const flags = new Set(argv.filter((a) => a.startsWith('--')));
const out = argv.find((a) => !a.startsWith('--'));
const num = (n, d) => {
  const hit = argv.find((a) => a.startsWith(`--${n}=`));
  return hit ? Number(hit.split('=')[1]) : d;
};

if (!out) {
  console.error('usage: node relight/tools/fixture.mjs <out-dir> '
    + '[--grain=N] [--sphere] [--drift] [--size=N] [--shots=N] [--flat]');
  process.exit(2);
}

const SIZE = num('size', 340);
const SHOTS = num('shots', 6);
const GRAIN = num('grain', 0);
const WITH_SPHERE = flags.has('--sphere');
const WITH_DRIFT = flags.has('--drift');
// --flat builds the degenerate rig on purpose: constant elevation makes the
// ambient column a constant multiple of Lz, the system is rank-deficient, and
// buildSolver refuses. It exists so the preflight's refusal can be tested.
const FLAT = flags.has('--flat');

const dirFrom = (azDeg, elDeg) => {
  const a = azDeg * Math.PI / 180, e = elDeg * Math.PI / 180;
  return [Math.cos(a) * Math.cos(e), Math.sin(a) * Math.cos(e), Math.sin(e)];
};

// Azimuths right round the circle, elevation alternating by 15° — the protocol's
// rig. Under --flat every elevation is the same and the solve must refuse.
const rig = [];
for (let i = 0; i < SHOTS; i++) {
  const az = (i * 360) / SHOTS;
  const el = FLAT ? 45 : (i % 2 ? 52.5 : 37.5);
  rig.push({ az, el });
}

const sphere = WITH_SPHERE
  ? { cx: Math.round(SIZE * 0.5), cy: Math.round(SIZE * 0.5), r: Math.round(SIZE * 0.30) }
  : null;

const S = synthesizeCaptureSet({
  width: SIZE, height: SIZE, seed: 7, pigmentDetail: 0.35, grain: GRAIN,
  lightDirs: rig.map((r) => dirFrom(r.az, r.el)),
  sphere,
});

mkdirSync(resolve(out), { recursive: true });

// Drift: knock one exposure sideways, to give registration something to find.
const drifts = rig.map((_, i) => (WITH_DRIFT && i === 2 ? { dx: 2.4, dy: -1.3 } : { dx: 0, dy: 0 }));

const exposures = [];
for (let i = 0; i < rig.length; i++) {
  const file = `shot-${String(i + 1).padStart(2, '0')}.png`;
  let data = S.images[i].data;
  if (drifts[i].dx || drifts[i].dy) {
    data = resample(data, SIZE, SIZE, drifts[i].dx, drifts[i].dy);
  }
  writeFileSync(join(resolve(out), file), encodePNG(data, SIZE, SIZE));
  exposures.push({ file, azimuth: rig[i].az, elevation: rig[i].el });
}

const manifest = {
  painting: 'synthetic bench surface (fixture)',
  material: `procedural canvas, pigmentDetail 0.35, grain ${GRAIN}`,
  shot: new Date().toISOString().slice(0, 10),
  notes: 'Generated by tools/fixture.mjs. The height field is known exactly, so this '
       + 'bundle is the one capture whose answer can be checked.',
  exposures,
  ...(sphere ? { sphere } : {}),
};
writeFileSync(join(resolve(out), 'capture.json'), JSON.stringify(manifest, null, 2) + '\n');

// The truth, for a harness that wants to check the answer rather than the plumbing.
const N = S.normals;
const nbuf = Buffer.alloc(N.length * 4);
for (let i = 0; i < N.length; i++) nbuf.writeFloatLE(N[i], i * 4);
writeFileSync(join(resolve(out), 'truth-normals.f32'), nbuf);

console.log(`wrote ${exposures.length} exposures + capture.json to ${resolve(out)}`);
console.log(`  ${SIZE}x${SIZE}, grain ${GRAIN}`
  + `${sphere ? `, sphere r=${sphere.r}` : ', no sphere'}`
  + `${WITH_DRIFT ? ', one frame drifted 2.4/-1.3px' : ''}`
  + `${FLAT ? ', CONSTANT ELEVATION (rank-deficient on purpose)' : ''}`);
console.log('  truth-normals.f32 holds the true normals as float32 xyz triples.');
